services:
  gitea:
    cap_drop:
      - ALL
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgresdb:5432
      - GITEA__database__NAME=$GITEA_POSTGRES_DATABASE
      - GITEA__database__USER=$GITEA_POSTGRES_USER
      - GITEA__database__PASSWD=$GITEA_POSTGRES_PASSWORD
      - GITEA__mailer__ENABLED=true
      - GITEA__mailer__FROM=gitea@<your domain>
      - GITEA__mailer__PROTOCOL=smtps
      - GITEA__mailer__SMTP_ADDR=$RESEND_HOST
      - GITEA__mailer__SMTP_PORT=$RESEND_PORT
      - GITEA__mailer__USER=$RESEND_USER
      - GITEA__mailer__PASSWD=$RESEND_API_KEY
    image: docker.gitea.com/gitea:1.26-rootless
    ports:
      - mode: ingress
        protocol: tcp
        published: 3000
        target: 3000
      - mode: ingress
        protocol: tcp
        published: 3002
        target: 2222
    privileged: False
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    user: '568:568'
    volumes:
      - bind:
          create_host_path: False
          propagation: rprivate
        read_only: False
        source: /mnt/main/apps/gitea/data
        target: /var/lib/gitea
        type: bind
      - bind:
          create_host_path: False
          propagation: rprivate
        read_only: False
        source: /mnt/main/apps/gitea/config
        target: /etc/gitea
        type: bind
      - bind:
          create_host_path: False
          propagation: rprivate
        read_only: False
        source: /etc/timezone
        target: /etc/timezone:ro
        type: bind
      - bind:
          create_host_path: False
          propagation: rprivate
        read_only: False
        source: /etc/localtime
        target: /etc/localtime:ro
        type: bind
    networks:
      - gitea-network
      - postgres-network
      - authentik-network
networks:
  gitea-network:
    name: gitea-network
  postgres-network:
    external: true
  authentik-network:
    external: true